version: '3.7'

services:
  postgres:
    image: postgres
    container_name: pinpoint-test
    restart: always
    ports:
      - "5440:5432"
    environment:
      - POSTGRES_DB=client
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testpass
