global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    scrape_interval: 5s 
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: postgres-exporter
    scrape_interval: 5s 
    static_configs:
      - targets: ["postgres-exporter:9187"]

  - job_name: "node"
    static_configs:
    - targets: ["node-exporter:9100"]

  - job_name: 'nginx-exporter'
    scrape_interval: 15s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['nginx-exporter:9113']