
service: send-image-to-slack

frameworkVersion: '3'

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-2

package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  send-image-to-slack:
    handler: bin/send-image-to-slack
    events:
      - http:
          path: image
          method: post