server:
  port: 8005

spring:
  application:
    name: minerva-service
  boot:
    admin:
      client:
        url: http://localhost:8080 #admin server url
        instance:
          name: Minerva Server #admin UI 에서 보여질 이름 설정
management:
  endpoints:
    web:
      exposure:
        include: "*" #노출시킬 endpoint, *는 전체 노출
  endpoint:
    health:
      show-details: always
request:
  url: "localhost"
  port: 8004
  path: "/luna/api/serviceName"

logging:
  file:
    name: "minerva-service.log"
  level:
    org:
      springframework:
        web:
          filter: DEBUG
