server:
  port: 8003

spring:
  application:
    name: jupiter-service
  boot:
    admin:
      client:
        url: http://localhost:8080 #admin server url
        instance:
          name: Jupiter Server #admin UI 에서 보여질 이름 설정
  management:
    endpoints:
      web:
        exposure:
          include: "*" #노출시킬 endpoint, *는 전체 노출
    endpoint:
      health:
        show-details: always

logging:
  file:
    name: "jupiter-service.log"
  level:
    org:
      springframework:
        web:
          filter: DEBUG