server:
  port: 8000

spring:
  application:
    name: aurora-service
  boot:
    admin:
      client:
        url: http://localhost:8080 #admin server url
        instance:
          name: Aurora Server #admin UI 에서 보여질 이름 설정
management:
  endpoints:
    web:
      exposure:
        include: "*" #노출시킬 endpoint, *는 전체 노출
  endpoint:
    health:
      show-details: always

request:
  url: "localhost"
  port: 8007
  path: "/neptune/api/userinfo/{id}"

logging:
  level:
    org.springframework.web: DEBUG
